# Generated by Django 5.0.6 on 2024-06-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_alter_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dob",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Masculino"),
                    ("female", "Feminino"),
                    ("other", "Não Informado"),
                ],
                default="male",
                max_length=20,
            ),
        ),
    ]
