# Generated by Django 5.0.2 on 2024-02-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images"),
        ),
    ]
