# Generated by Django 5.0.2 on 2024-02-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_images"),
        ),
    ]
